apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: yodelling-owl-python-gitops-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/yodelling-owl-python-gitops